repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      # - id: pretty-format-json

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--in-place",
            "--recursive",
            ".",
          ]
  - repo: local
    hooks:
      - id: check-variable-naming
        name: Check variable naming
        entry: python coreutils/pre_commit/precommit_check_variable_naming.py
        language: python
        pass_filenames: true
  - repo: local
    hooks:
      - id: delete-empty-files
        name: Delete Empty Python Files
        entry: python coreutils/pre_commit/delete_empty_files.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: check-duplicate-classes
        name: Delete Empty Python Files
        entry: python coreutils/pre_commit/check_duplicate_class_names.py
        language: system
        types: [python]
